/*
 * This file is generated by jOOQ.
 */
package org.ort.school.crm.jooq.model;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.ort.school.crm.jooq.model.tables.Grade;
import org.ort.school.crm.jooq.model.tables.Group;
import org.ort.school.crm.jooq.model.tables.GroupStudent;
import org.ort.school.crm.jooq.model.tables.Parent;
import org.ort.school.crm.jooq.model.tables.ParentGrade;
import org.ort.school.crm.jooq.model.tables.ParentStudent;
import org.ort.school.crm.jooq.model.tables.Role;
import org.ort.school.crm.jooq.model.tables.Student;
import org.ort.school.crm.jooq.model.tables.User;
import org.ort.school.crm.jooq.model.tables.UserRole;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONSTRAINT_INDEX_4 = Indexes0.CONSTRAINT_INDEX_4;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index CONSTRAINT_INDEX_48 = Indexes0.CONSTRAINT_INDEX_48;
    public static final Index CONSTRAINT_INDEX_48E = Indexes0.CONSTRAINT_INDEX_48E;
    public static final Index GR_G = Indexes0.GR_G;
    public static final Index GR_S = Indexes0.GR_S;
    public static final Index CONSTRAINT_INDEX_8 = Indexes0.CONSTRAINT_INDEX_8;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index CONSTRAINT_INDEX_1 = Indexes0.CONSTRAINT_INDEX_1;
    public static final Index CONSTRAINT_INDEX_13 = Indexes0.CONSTRAINT_INDEX_13;
    public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;
    public static final Index CONSTRAINT_INDEX_19 = Indexes0.CONSTRAINT_INDEX_19;
    public static final Index CONSTRAINT_INDEX_194 = Indexes0.CONSTRAINT_INDEX_194;
    public static final Index PRIMARY_KEY_19 = Indexes0.PRIMARY_KEY_19;
    public static final Index P_S_PID = Indexes0.P_S_PID;
    public static final Index P_S_SID = Indexes0.P_S_SID;
    public static final Index PRIMARY_KEY_26 = Indexes0.PRIMARY_KEY_26;
    public static final Index CONSTRAINT_INDEX_BA = Indexes0.CONSTRAINT_INDEX_BA;
    public static final Index CONSTRAINT_INDEX_BAC = Indexes0.CONSTRAINT_INDEX_BAC;
    public static final Index PRIMARY_KEY_BA = Indexes0.PRIMARY_KEY_BA;
    public static final Index STUDENT_GRADE = Indexes0.STUDENT_GRADE;
    public static final Index CONSTRAINT_INDEX_2 = Indexes0.CONSTRAINT_INDEX_2;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index USER_NAME = Indexes0.USER_NAME;
    public static final Index CONSTRAINT_INDEX_B = Indexes0.CONSTRAINT_INDEX_B;
    public static final Index CONSTRAINT_INDEX_BC = Indexes0.CONSTRAINT_INDEX_BC;
    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;
    public static final Index U_R_ROLE = Indexes0.U_R_ROLE;
    public static final Index U_R_UID = Indexes0.U_R_UID;
    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONSTRAINT_INDEX_4 = Internal.createIndex("CONSTRAINT_INDEX_4", Grade.GRADE, new OrderField[] { Grade.GRADE.GRADE_NO, Grade.GRADE.GRADE_LETTER }, true);
        public static Index PRIMARY_KEY_4 = Internal.createIndex("PRIMARY_KEY_4", Grade.GRADE, new OrderField[] { Grade.GRADE.ID }, true);
        public static Index CONSTRAINT_INDEX_48 = Internal.createIndex("CONSTRAINT_INDEX_48", GroupStudent.GROUP_STUDENT, new OrderField[] { GroupStudent.GROUP_STUDENT.STUDENT_ID }, false);
        public static Index CONSTRAINT_INDEX_48E = Internal.createIndex("CONSTRAINT_INDEX_48E", GroupStudent.GROUP_STUDENT, new OrderField[] { GroupStudent.GROUP_STUDENT.GROUP_ID }, false);
        public static Index GR_G = Internal.createIndex("GR_G", GroupStudent.GROUP_STUDENT, new OrderField[] { GroupStudent.GROUP_STUDENT.GROUP_ID }, false);
        public static Index GR_S = Internal.createIndex("GR_S", GroupStudent.GROUP_STUDENT, new OrderField[] { GroupStudent.GROUP_STUDENT.STUDENT_ID }, false);
        public static Index CONSTRAINT_INDEX_8 = Internal.createIndex("CONSTRAINT_INDEX_8", Parent.PARENT, new OrderField[] { Parent.PARENT.EMAIL }, true);
        public static Index PRIMARY_KEY_8 = Internal.createIndex("PRIMARY_KEY_8", Parent.PARENT, new OrderField[] { Parent.PARENT.ID }, true);
        public static Index CONSTRAINT_INDEX_1 = Internal.createIndex("CONSTRAINT_INDEX_1", ParentGrade.PARENT_GRADE, new OrderField[] { ParentGrade.PARENT_GRADE.PARENT_ID }, false);
        public static Index CONSTRAINT_INDEX_13 = Internal.createIndex("CONSTRAINT_INDEX_13", ParentGrade.PARENT_GRADE, new OrderField[] { ParentGrade.PARENT_GRADE.GRADE_ID }, false);
        public static Index PRIMARY_KEY_1 = Internal.createIndex("PRIMARY_KEY_1", ParentGrade.PARENT_GRADE, new OrderField[] { ParentGrade.PARENT_GRADE.PARENT_ID, ParentGrade.PARENT_GRADE.GRADE_ID }, true);
        public static Index CONSTRAINT_INDEX_19 = Internal.createIndex("CONSTRAINT_INDEX_19", ParentStudent.PARENT_STUDENT, new OrderField[] { ParentStudent.PARENT_STUDENT.PARENT_ID }, false);
        public static Index CONSTRAINT_INDEX_194 = Internal.createIndex("CONSTRAINT_INDEX_194", ParentStudent.PARENT_STUDENT, new OrderField[] { ParentStudent.PARENT_STUDENT.STUDENT_ID }, false);
        public static Index PRIMARY_KEY_19 = Internal.createIndex("PRIMARY_KEY_19", ParentStudent.PARENT_STUDENT, new OrderField[] { ParentStudent.PARENT_STUDENT.PARENT_ID, ParentStudent.PARENT_STUDENT.STUDENT_ID }, true);
        public static Index P_S_PID = Internal.createIndex("P_S_PID", ParentStudent.PARENT_STUDENT, new OrderField[] { ParentStudent.PARENT_STUDENT.PARENT_ID }, false);
        public static Index P_S_SID = Internal.createIndex("P_S_SID", ParentStudent.PARENT_STUDENT, new OrderField[] { ParentStudent.PARENT_STUDENT.STUDENT_ID }, false);
        public static Index PRIMARY_KEY_26 = Internal.createIndex("PRIMARY_KEY_26", Role.ROLE, new OrderField[] { Role.ROLE.NAME }, true);
        public static Index CONSTRAINT_INDEX_BA = Internal.createIndex("CONSTRAINT_INDEX_BA", Student.STUDENT, new OrderField[] { Student.STUDENT.GRADE_ID }, false);
        public static Index CONSTRAINT_INDEX_BAC = Internal.createIndex("CONSTRAINT_INDEX_BAC", Student.STUDENT, new OrderField[] { Student.STUDENT.FIRSTNAME, Student.STUDENT.LASTNAME, Student.STUDENT.PATRONYMIC, Student.STUDENT.GRADE_ID }, true);
        public static Index PRIMARY_KEY_BA = Internal.createIndex("PRIMARY_KEY_BA", Student.STUDENT, new OrderField[] { Student.STUDENT.ID }, true);
        public static Index STUDENT_GRADE = Internal.createIndex("STUDENT_GRADE", Student.STUDENT, new OrderField[] { Student.STUDENT.GRADE_ID }, false);
        public static Index CONSTRAINT_INDEX_2 = Internal.createIndex("CONSTRAINT_INDEX_2", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_NAME = Internal.createIndex("USER_NAME", User.USER, new OrderField[] { User.USER.USERNAME }, false);
        public static Index CONSTRAINT_INDEX_B = Internal.createIndex("CONSTRAINT_INDEX_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID }, false);
        public static Index CONSTRAINT_INDEX_BC = Internal.createIndex("CONSTRAINT_INDEX_BC", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ROLE }, false);
        public static Index PRIMARY_KEY_B = Internal.createIndex("PRIMARY_KEY_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID, UserRole.USER_ROLE.ROLE }, true);
        public static Index U_R_ROLE = Internal.createIndex("U_R_ROLE", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ROLE }, false);
        public static Index U_R_UID = Internal.createIndex("U_R_UID", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID }, false);
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", Group.GROUP, new OrderField[] { Group.GROUP.ID }, true);
    }
}
