/*
 * This file is generated by jOOQ.
*/
package org.ort.school.crm.jooq.model;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;
import org.ort.school.crm.jooq.model.tables.Grade;
import org.ort.school.crm.jooq.model.tables.Parent;
import org.ort.school.crm.jooq.model.tables.ParentGrade;
import org.ort.school.crm.jooq.model.tables.Role;
import org.ort.school.crm.jooq.model.tables.SchemaVersion;
import org.ort.school.crm.jooq.model.tables.User;
import org.ort.school.crm.jooq.model.tables.UserRole;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONSTRAINT_INDEX_4 = Indexes0.CONSTRAINT_INDEX_4;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index PRIMARY_KEY_8 = Indexes0.PRIMARY_KEY_8;
    public static final Index CONSTRAINT_INDEX_1 = Indexes0.CONSTRAINT_INDEX_1;
    public static final Index CONSTRAINT_INDEX_13 = Indexes0.CONSTRAINT_INDEX_13;
    public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;
    public static final Index PRIMARY_KEY_26 = Indexes0.PRIMARY_KEY_26;
    public static final Index CONSTRAINT_INDEX_2 = Indexes0.CONSTRAINT_INDEX_2;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index USER_NAME = Indexes0.USER_NAME;
    public static final Index CONSTRAINT_INDEX_B = Indexes0.CONSTRAINT_INDEX_B;
    public static final Index CONSTRAINT_INDEX_BC = Indexes0.CONSTRAINT_INDEX_BC;
    public static final Index PRIMARY_KEY_B = Indexes0.PRIMARY_KEY_B;
    public static final Index U_R_ROLE = Indexes0.U_R_ROLE;
    public static final Index U_R_UID = Indexes0.U_R_UID;
    public static final Index PRIMARY_KEY_6 = Indexes0.PRIMARY_KEY_6;
    public static final Index SCHEMA_VERSION_S_IDX = Indexes0.SCHEMA_VERSION_S_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index CONSTRAINT_INDEX_4 = createIndex("CONSTRAINT_INDEX_4", Grade.GRADE, new OrderField[] { Grade.GRADE.GRADE_NO, Grade.GRADE.GRADE_LETTER }, true);
        public static Index PRIMARY_KEY_4 = createIndex("PRIMARY_KEY_4", Grade.GRADE, new OrderField[] { Grade.GRADE.ID }, true);
        public static Index PRIMARY_KEY_8 = createIndex("PRIMARY_KEY_8", Parent.PARENT, new OrderField[] { Parent.PARENT.ID }, true);
        public static Index CONSTRAINT_INDEX_1 = createIndex("CONSTRAINT_INDEX_1", ParentGrade.PARENT_GRADE, new OrderField[] { ParentGrade.PARENT_GRADE.PARENT_ID }, false);
        public static Index CONSTRAINT_INDEX_13 = createIndex("CONSTRAINT_INDEX_13", ParentGrade.PARENT_GRADE, new OrderField[] { ParentGrade.PARENT_GRADE.GRADE_ID }, false);
        public static Index PRIMARY_KEY_1 = createIndex("PRIMARY_KEY_1", ParentGrade.PARENT_GRADE, new OrderField[] { ParentGrade.PARENT_GRADE.PARENT_ID, ParentGrade.PARENT_GRADE.GRADE_ID }, true);
        public static Index PRIMARY_KEY_26 = createIndex("PRIMARY_KEY_26", Role.ROLE, new OrderField[] { Role.ROLE.NAME }, true);
        public static Index CONSTRAINT_INDEX_2 = createIndex("CONSTRAINT_INDEX_2", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index PRIMARY_KEY_2 = createIndex("PRIMARY_KEY_2", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_NAME = createIndex("USER_NAME", User.USER, new OrderField[] { User.USER.USERNAME }, false);
        public static Index CONSTRAINT_INDEX_B = createIndex("CONSTRAINT_INDEX_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID }, false);
        public static Index CONSTRAINT_INDEX_BC = createIndex("CONSTRAINT_INDEX_BC", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ROLE }, false);
        public static Index PRIMARY_KEY_B = createIndex("PRIMARY_KEY_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID, UserRole.USER_ROLE.ROLE }, true);
        public static Index U_R_ROLE = createIndex("U_R_ROLE", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ROLE }, false);
        public static Index U_R_UID = createIndex("U_R_UID", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID }, false);
        public static Index PRIMARY_KEY_6 = createIndex("PRIMARY_KEY_6", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.INSTALLED_RANK }, true);
        public static Index SCHEMA_VERSION_S_IDX = createIndex("schema_version_s_idx", SchemaVersion.SCHEMA_VERSION, new OrderField[] { SchemaVersion.SCHEMA_VERSION.SUCCESS }, false);
    }
}
