/*
 * This file is generated by jOOQ.
 */
package org.ort.school.crm.jooq.model;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.ort.school.crm.jooq.model.tables.Grade;
import org.ort.school.crm.jooq.model.tables.Group;
import org.ort.school.crm.jooq.model.tables.GroupStudent;
import org.ort.school.crm.jooq.model.tables.Parent;
import org.ort.school.crm.jooq.model.tables.ParentStudent;
import org.ort.school.crm.jooq.model.tables.Role;
import org.ort.school.crm.jooq.model.tables.Student;
import org.ort.school.crm.jooq.model.tables.User;
import org.ort.school.crm.jooq.model.tables.UserRole;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GRADE_GRADE_NO_GRADE_LETTER_KEY = Indexes0.GRADE_GRADE_NO_GRADE_LETTER_KEY;
    public static final Index GRADE_PKEY = Indexes0.GRADE_PKEY;
    public static final Index GROUP_NAME_UQ = Indexes0.GROUP_NAME_UQ;
    public static final Index GROUP_PKEY = Indexes0.GROUP_PKEY;
    public static final Index GR_G = Indexes0.GR_G;
    public static final Index GR_S = Indexes0.GR_S;
    public static final Index PARENT_EMAIL_KEY = Indexes0.PARENT_EMAIL_KEY;
    public static final Index PARENT_LASTNAME_FIRSTNAME_EMAIL_PATRONYMIC_KEY = Indexes0.PARENT_LASTNAME_FIRSTNAME_EMAIL_PATRONYMIC_KEY;
    public static final Index PARENT_PKEY = Indexes0.PARENT_PKEY;
    public static final Index P_S_PID = Indexes0.P_S_PID;
    public static final Index P_S_SID = Indexes0.P_S_SID;
    public static final Index PARENT_STUDENT_PKEY = Indexes0.PARENT_STUDENT_PKEY;
    public static final Index ROLE_PKEY = Indexes0.ROLE_PKEY;
    public static final Index STUDENT_FIRSTNAME_LASTNAME_PATRONYMIC_GRADE_ID_KEY = Indexes0.STUDENT_FIRSTNAME_LASTNAME_PATRONYMIC_GRADE_ID_KEY;
    public static final Index STUDENT_GRADE = Indexes0.STUDENT_GRADE;
    public static final Index STUDENT_PKEY = Indexes0.STUDENT_PKEY;
    public static final Index USER_NAME = Indexes0.USER_NAME;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;
    public static final Index USER_USERNAME_KEY = Indexes0.USER_USERNAME_KEY;
    public static final Index U_R_ROLE = Indexes0.U_R_ROLE;
    public static final Index U_R_UID = Indexes0.U_R_UID;
    public static final Index USER_ROLE_PKEY = Indexes0.USER_ROLE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index GRADE_GRADE_NO_GRADE_LETTER_KEY = Internal.createIndex("grade_grade_no_grade_letter_key", Grade.GRADE, new OrderField[] { Grade.GRADE.GRADE_NO, Grade.GRADE.GRADE_LETTER }, true);
        public static Index GRADE_PKEY = Internal.createIndex("grade_pkey", Grade.GRADE, new OrderField[] { Grade.GRADE.ID }, true);
        public static Index GROUP_NAME_UQ = Internal.createIndex("group_name_uq", Group.GROUP, new OrderField[] { Group.GROUP.NAME }, true);
        public static Index GROUP_PKEY = Internal.createIndex("group_pkey", Group.GROUP, new OrderField[] { Group.GROUP.ID }, true);
        public static Index GR_G = Internal.createIndex("gr_g", GroupStudent.GROUP_STUDENT, new OrderField[] { GroupStudent.GROUP_STUDENT.GROUP_ID }, false);
        public static Index GR_S = Internal.createIndex("gr_s", GroupStudent.GROUP_STUDENT, new OrderField[] { GroupStudent.GROUP_STUDENT.STUDENT_ID }, false);
        public static Index PARENT_EMAIL_KEY = Internal.createIndex("parent_email_key", Parent.PARENT, new OrderField[] { Parent.PARENT.EMAIL }, true);
        public static Index PARENT_LASTNAME_FIRSTNAME_EMAIL_PATRONYMIC_KEY = Internal.createIndex("parent_lastname_firstname_email_patronymic_key", Parent.PARENT, new OrderField[] { Parent.PARENT.LASTNAME, Parent.PARENT.FIRSTNAME, Parent.PARENT.EMAIL, Parent.PARENT.PATRONYMIC }, true);
        public static Index PARENT_PKEY = Internal.createIndex("parent_pkey", Parent.PARENT, new OrderField[] { Parent.PARENT.ID }, true);
        public static Index P_S_PID = Internal.createIndex("p_s_pid", ParentStudent.PARENT_STUDENT, new OrderField[] { ParentStudent.PARENT_STUDENT.PARENT_ID }, false);
        public static Index P_S_SID = Internal.createIndex("p_s_sid", ParentStudent.PARENT_STUDENT, new OrderField[] { ParentStudent.PARENT_STUDENT.STUDENT_ID }, false);
        public static Index PARENT_STUDENT_PKEY = Internal.createIndex("parent_student_pkey", ParentStudent.PARENT_STUDENT, new OrderField[] { ParentStudent.PARENT_STUDENT.PARENT_ID, ParentStudent.PARENT_STUDENT.STUDENT_ID }, true);
        public static Index ROLE_PKEY = Internal.createIndex("role_pkey", Role.ROLE, new OrderField[] { Role.ROLE.NAME }, true);
        public static Index STUDENT_FIRSTNAME_LASTNAME_PATRONYMIC_GRADE_ID_KEY = Internal.createIndex("student_firstname_lastname_patronymic_grade_id_key", Student.STUDENT, new OrderField[] { Student.STUDENT.FIRSTNAME, Student.STUDENT.LASTNAME, Student.STUDENT.PATRONYMIC, Student.STUDENT.GRADE_ID }, true);
        public static Index STUDENT_GRADE = Internal.createIndex("student_grade", Student.STUDENT, new OrderField[] { Student.STUDENT.GRADE_ID }, false);
        public static Index STUDENT_PKEY = Internal.createIndex("student_pkey", Student.STUDENT, new OrderField[] { Student.STUDENT.ID }, true);
        public static Index USER_NAME = Internal.createIndex("user_name", User.USER, new OrderField[] { User.USER.USERNAME }, false);
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_USERNAME_KEY = Internal.createIndex("user_username_key", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index U_R_ROLE = Internal.createIndex("u_r_role", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ROLE }, false);
        public static Index U_R_UID = Internal.createIndex("u_r_uid", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID }, false);
        public static Index USER_ROLE_PKEY = Internal.createIndex("user_role_pkey", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID, UserRole.USER_ROLE.ROLE }, true);
    }
}
