/*
 * This file is generated by jOOQ.
 */
package org.ort.school.crm.jooq.model;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.ort.school.crm.jooq.model.tables.Grade;
import org.ort.school.crm.jooq.model.tables.Group;
import org.ort.school.crm.jooq.model.tables.GroupStudent;
import org.ort.school.crm.jooq.model.tables.Parent;
import org.ort.school.crm.jooq.model.tables.ParentStudent;
import org.ort.school.crm.jooq.model.tables.Role;
import org.ort.school.crm.jooq.model.tables.Student;
import org.ort.school.crm.jooq.model.tables.User;
import org.ort.school.crm.jooq.model.tables.UserRole;
import org.ort.school.crm.jooq.model.tables.records.GradeRecord;
import org.ort.school.crm.jooq.model.tables.records.GroupRecord;
import org.ort.school.crm.jooq.model.tables.records.GroupStudentRecord;
import org.ort.school.crm.jooq.model.tables.records.ParentRecord;
import org.ort.school.crm.jooq.model.tables.records.ParentStudentRecord;
import org.ort.school.crm.jooq.model.tables.records.RoleRecord;
import org.ort.school.crm.jooq.model.tables.records.StudentRecord;
import org.ort.school.crm.jooq.model.tables.records.UserRecord;
import org.ort.school.crm.jooq.model.tables.records.UserRoleRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<GradeRecord, Integer> IDENTITY_GRADE = Identities0.IDENTITY_GRADE;
    public static final Identity<GroupRecord, Long> IDENTITY_GROUP = Identities0.IDENTITY_GROUP;
    public static final Identity<ParentRecord, Long> IDENTITY_PARENT = Identities0.IDENTITY_PARENT;
    public static final Identity<StudentRecord, Long> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;
    public static final Identity<UserRecord, Long> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GradeRecord> GRADE_PKEY = UniqueKeys0.GRADE_PKEY;
    public static final UniqueKey<GradeRecord> GRADE_GRADE_NO_GRADE_LETTER_KEY = UniqueKeys0.GRADE_GRADE_NO_GRADE_LETTER_KEY;
    public static final UniqueKey<GroupRecord> GROUP_PKEY = UniqueKeys0.GROUP_PKEY;
    public static final UniqueKey<ParentRecord> PARENT_PKEY = UniqueKeys0.PARENT_PKEY;
    public static final UniqueKey<ParentRecord> PARENT_LASTNAME_FIRSTNAME_EMAIL_PATRONYMIC_KEY = UniqueKeys0.PARENT_LASTNAME_FIRSTNAME_EMAIL_PATRONYMIC_KEY;
    public static final UniqueKey<ParentRecord> PARENT_EMAIL_KEY = UniqueKeys0.PARENT_EMAIL_KEY;
    public static final UniqueKey<ParentStudentRecord> PARENT_STUDENT_PKEY = UniqueKeys0.PARENT_STUDENT_PKEY;
    public static final UniqueKey<RoleRecord> ROLE_PKEY = UniqueKeys0.ROLE_PKEY;
    public static final UniqueKey<StudentRecord> STUDENT_PKEY = UniqueKeys0.STUDENT_PKEY;
    public static final UniqueKey<StudentRecord> STUDENT_FIRSTNAME_LASTNAME_PATRONYMIC_GRADE_ID_KEY = UniqueKeys0.STUDENT_FIRSTNAME_LASTNAME_PATRONYMIC_GRADE_ID_KEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;
    public static final UniqueKey<UserRecord> USER_USERNAME_KEY = UniqueKeys0.USER_USERNAME_KEY;
    public static final UniqueKey<UserRoleRecord> USER_ROLE_PKEY = UniqueKeys0.USER_ROLE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GroupStudentRecord, StudentRecord> GROUP_STUDENT__GROUP_STUDENT_STUDENT_ID_FKEY = ForeignKeys0.GROUP_STUDENT__GROUP_STUDENT_STUDENT_ID_FKEY;
    public static final ForeignKey<GroupStudentRecord, GroupRecord> GROUP_STUDENT__GROUP_STUDENT_GROUP_ID_FKEY = ForeignKeys0.GROUP_STUDENT__GROUP_STUDENT_GROUP_ID_FKEY;
    public static final ForeignKey<ParentStudentRecord, ParentRecord> PARENT_STUDENT__PARENT_STUDENT_PARENT_ID_FKEY = ForeignKeys0.PARENT_STUDENT__PARENT_STUDENT_PARENT_ID_FKEY;
    public static final ForeignKey<ParentStudentRecord, StudentRecord> PARENT_STUDENT__PARENT_STUDENT_STUDENT_ID_FKEY = ForeignKeys0.PARENT_STUDENT__PARENT_STUDENT_STUDENT_ID_FKEY;
    public static final ForeignKey<StudentRecord, GradeRecord> STUDENT__STUDENT_GRADE_ID_FKEY = ForeignKeys0.STUDENT__STUDENT_GRADE_ID_FKEY;
    public static final ForeignKey<UserRoleRecord, UserRecord> USER_ROLE__USER_ROLE_USER_ID_FKEY = ForeignKeys0.USER_ROLE__USER_ROLE_USER_ID_FKEY;
    public static final ForeignKey<UserRoleRecord, RoleRecord> USER_ROLE__USER_ROLE_ROLE_FKEY = ForeignKeys0.USER_ROLE__USER_ROLE_ROLE_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<GradeRecord, Integer> IDENTITY_GRADE = Internal.createIdentity(Grade.GRADE, Grade.GRADE.ID);
        public static Identity<GroupRecord, Long> IDENTITY_GROUP = Internal.createIdentity(Group.GROUP, Group.GROUP.ID);
        public static Identity<ParentRecord, Long> IDENTITY_PARENT = Internal.createIdentity(Parent.PARENT, Parent.PARENT.ID);
        public static Identity<StudentRecord, Long> IDENTITY_STUDENT = Internal.createIdentity(Student.STUDENT, Student.STUDENT.ID);
        public static Identity<UserRecord, Long> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<GradeRecord> GRADE_PKEY = Internal.createUniqueKey(Grade.GRADE, "grade_pkey", Grade.GRADE.ID);
        public static final UniqueKey<GradeRecord> GRADE_GRADE_NO_GRADE_LETTER_KEY = Internal.createUniqueKey(Grade.GRADE, "grade_grade_no_grade_letter_key", Grade.GRADE.GRADE_NO, Grade.GRADE.GRADE_LETTER);
        public static final UniqueKey<GroupRecord> GROUP_PKEY = Internal.createUniqueKey(Group.GROUP, "group_pkey", Group.GROUP.ID);
        public static final UniqueKey<ParentRecord> PARENT_PKEY = Internal.createUniqueKey(Parent.PARENT, "parent_pkey", Parent.PARENT.ID);
        public static final UniqueKey<ParentRecord> PARENT_LASTNAME_FIRSTNAME_EMAIL_PATRONYMIC_KEY = Internal.createUniqueKey(Parent.PARENT, "parent_lastname_firstname_email_patronymic_key", Parent.PARENT.LASTNAME, Parent.PARENT.FIRSTNAME, Parent.PARENT.EMAIL, Parent.PARENT.PATRONYMIC);
        public static final UniqueKey<ParentRecord> PARENT_EMAIL_KEY = Internal.createUniqueKey(Parent.PARENT, "parent_email_key", Parent.PARENT.EMAIL);
        public static final UniqueKey<ParentStudentRecord> PARENT_STUDENT_PKEY = Internal.createUniqueKey(ParentStudent.PARENT_STUDENT, "parent_student_pkey", ParentStudent.PARENT_STUDENT.PARENT_ID, ParentStudent.PARENT_STUDENT.STUDENT_ID);
        public static final UniqueKey<RoleRecord> ROLE_PKEY = Internal.createUniqueKey(Role.ROLE, "role_pkey", Role.ROLE.NAME);
        public static final UniqueKey<StudentRecord> STUDENT_PKEY = Internal.createUniqueKey(Student.STUDENT, "student_pkey", Student.STUDENT.ID);
        public static final UniqueKey<StudentRecord> STUDENT_FIRSTNAME_LASTNAME_PATRONYMIC_GRADE_ID_KEY = Internal.createUniqueKey(Student.STUDENT, "student_firstname_lastname_patronymic_grade_id_key", Student.STUDENT.FIRSTNAME, Student.STUDENT.LASTNAME, Student.STUDENT.PATRONYMIC, Student.STUDENT.GRADE_ID);
        public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, "user_pkey", User.USER.ID);
        public static final UniqueKey<UserRecord> USER_USERNAME_KEY = Internal.createUniqueKey(User.USER, "user_username_key", User.USER.USERNAME);
        public static final UniqueKey<UserRoleRecord> USER_ROLE_PKEY = Internal.createUniqueKey(UserRole.USER_ROLE, "user_role_pkey", UserRole.USER_ROLE.USER_ID, UserRole.USER_ROLE.ROLE);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<GroupStudentRecord, StudentRecord> GROUP_STUDENT__GROUP_STUDENT_STUDENT_ID_FKEY = Internal.createForeignKey(org.ort.school.crm.jooq.model.Keys.STUDENT_PKEY, GroupStudent.GROUP_STUDENT, "group_student__group_student_student_id_fkey", GroupStudent.GROUP_STUDENT.STUDENT_ID);
        public static final ForeignKey<GroupStudentRecord, GroupRecord> GROUP_STUDENT__GROUP_STUDENT_GROUP_ID_FKEY = Internal.createForeignKey(org.ort.school.crm.jooq.model.Keys.GROUP_PKEY, GroupStudent.GROUP_STUDENT, "group_student__group_student_group_id_fkey", GroupStudent.GROUP_STUDENT.GROUP_ID);
        public static final ForeignKey<ParentStudentRecord, ParentRecord> PARENT_STUDENT__PARENT_STUDENT_PARENT_ID_FKEY = Internal.createForeignKey(org.ort.school.crm.jooq.model.Keys.PARENT_PKEY, ParentStudent.PARENT_STUDENT, "parent_student__parent_student_parent_id_fkey", ParentStudent.PARENT_STUDENT.PARENT_ID);
        public static final ForeignKey<ParentStudentRecord, StudentRecord> PARENT_STUDENT__PARENT_STUDENT_STUDENT_ID_FKEY = Internal.createForeignKey(org.ort.school.crm.jooq.model.Keys.STUDENT_PKEY, ParentStudent.PARENT_STUDENT, "parent_student__parent_student_student_id_fkey", ParentStudent.PARENT_STUDENT.STUDENT_ID);
        public static final ForeignKey<StudentRecord, GradeRecord> STUDENT__STUDENT_GRADE_ID_FKEY = Internal.createForeignKey(org.ort.school.crm.jooq.model.Keys.GRADE_PKEY, Student.STUDENT, "student__student_grade_id_fkey", Student.STUDENT.GRADE_ID);
        public static final ForeignKey<UserRoleRecord, UserRecord> USER_ROLE__USER_ROLE_USER_ID_FKEY = Internal.createForeignKey(org.ort.school.crm.jooq.model.Keys.USER_PKEY, UserRole.USER_ROLE, "user_role__user_role_user_id_fkey", UserRole.USER_ROLE.USER_ID);
        public static final ForeignKey<UserRoleRecord, RoleRecord> USER_ROLE__USER_ROLE_ROLE_FKEY = Internal.createForeignKey(org.ort.school.crm.jooq.model.Keys.ROLE_PKEY, UserRole.USER_ROLE, "user_role__user_role_role_fkey", UserRole.USER_ROLE.ROLE);
    }
}
