/*
 * This file is generated by jOOQ.
 */
package org.ort.school.crm.jooq.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.ort.school.crm.jooq.model.tables.Grade;
import org.ort.school.crm.jooq.model.tables.Group;
import org.ort.school.crm.jooq.model.tables.GroupStudent;
import org.ort.school.crm.jooq.model.tables.Parent;
import org.ort.school.crm.jooq.model.tables.ParentGrade;
import org.ort.school.crm.jooq.model.tables.ParentStudent;
import org.ort.school.crm.jooq.model.tables.Role;
import org.ort.school.crm.jooq.model.tables.Student;
import org.ort.school.crm.jooq.model.tables.User;
import org.ort.school.crm.jooq.model.tables.UserRole;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1555300796;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.GRADE</code>.
     */
    public final Grade GRADE = org.ort.school.crm.jooq.model.tables.Grade.GRADE;

    /**
     * The table <code>PUBLIC.GROUP_STUDENT</code>.
     */
    public final GroupStudent GROUP_STUDENT = org.ort.school.crm.jooq.model.tables.GroupStudent.GROUP_STUDENT;

    /**
     * The table <code>PUBLIC.PARENT</code>.
     */
    public final Parent PARENT = org.ort.school.crm.jooq.model.tables.Parent.PARENT;

    /**
     * The table <code>PUBLIC.PARENT_GRADE</code>.
     */
    public final ParentGrade PARENT_GRADE = org.ort.school.crm.jooq.model.tables.ParentGrade.PARENT_GRADE;

    /**
     * The table <code>PUBLIC.PARENT_STUDENT</code>.
     */
    public final ParentStudent PARENT_STUDENT = org.ort.school.crm.jooq.model.tables.ParentStudent.PARENT_STUDENT;

    /**
     * The table <code>PUBLIC.ROLE</code>.
     */
    public final Role ROLE = org.ort.school.crm.jooq.model.tables.Role.ROLE;

    /**
     * The table <code>PUBLIC.STUDENT</code>.
     */
    public final Student STUDENT = org.ort.school.crm.jooq.model.tables.Student.STUDENT;

    /**
     * The table <code>PUBLIC.USER</code>.
     */
    public final User USER = org.ort.school.crm.jooq.model.tables.User.USER;

    /**
     * The table <code>PUBLIC.USER_ROLE</code>.
     */
    public final UserRole USER_ROLE = org.ort.school.crm.jooq.model.tables.UserRole.USER_ROLE;

    /**
     * The table <code>PUBLIC.group</code>.
     */
    public final Group GROUP = org.ort.school.crm.jooq.model.tables.Group.GROUP;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Grade.GRADE,
            GroupStudent.GROUP_STUDENT,
            Parent.PARENT,
            ParentGrade.PARENT_GRADE,
            ParentStudent.PARENT_STUDENT,
            Role.ROLE,
            Student.STUDENT,
            User.USER,
            UserRole.USER_ROLE,
            Group.GROUP);
    }
}
