/*
 * This file is generated by jOOQ.
 */
package org.ort.school.crm.jooq.model;


import javax.annotation.Generated;

import org.ort.school.crm.jooq.model.tables.Grade;
import org.ort.school.crm.jooq.model.tables.Group;
import org.ort.school.crm.jooq.model.tables.GroupStudent;
import org.ort.school.crm.jooq.model.tables.Parent;
import org.ort.school.crm.jooq.model.tables.ParentStudent;
import org.ort.school.crm.jooq.model.tables.Role;
import org.ort.school.crm.jooq.model.tables.Student;
import org.ort.school.crm.jooq.model.tables.User;
import org.ort.school.crm.jooq.model.tables.UserRole;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.grade</code>.
     */
    public static final Grade GRADE = org.ort.school.crm.jooq.model.tables.Grade.GRADE;

    /**
     * The table <code>public.group</code>.
     */
    public static final Group GROUP = org.ort.school.crm.jooq.model.tables.Group.GROUP;

    /**
     * The table <code>public.group_student</code>.
     */
    public static final GroupStudent GROUP_STUDENT = org.ort.school.crm.jooq.model.tables.GroupStudent.GROUP_STUDENT;

    /**
     * The table <code>public.parent</code>.
     */
    public static final Parent PARENT = org.ort.school.crm.jooq.model.tables.Parent.PARENT;

    /**
     * The table <code>public.parent_student</code>.
     */
    public static final ParentStudent PARENT_STUDENT = org.ort.school.crm.jooq.model.tables.ParentStudent.PARENT_STUDENT;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = org.ort.school.crm.jooq.model.tables.Role.ROLE;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = org.ort.school.crm.jooq.model.tables.Student.STUDENT;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = org.ort.school.crm.jooq.model.tables.User.USER;

    /**
     * The table <code>public.user_role</code>.
     */
    public static final UserRole USER_ROLE = org.ort.school.crm.jooq.model.tables.UserRole.USER_ROLE;
}
