/*
 * This file is generated by jOOQ.
 */
package org.ort.school.crm.jooq.model;


import javax.annotation.Generated;

import org.ort.school.crm.jooq.model.tables.Grade;
import org.ort.school.crm.jooq.model.tables.Group;
import org.ort.school.crm.jooq.model.tables.GroupStudent;
import org.ort.school.crm.jooq.model.tables.Parent;
import org.ort.school.crm.jooq.model.tables.ParentGrade;
import org.ort.school.crm.jooq.model.tables.ParentStudent;
import org.ort.school.crm.jooq.model.tables.Role;
import org.ort.school.crm.jooq.model.tables.Student;
import org.ort.school.crm.jooq.model.tables.User;
import org.ort.school.crm.jooq.model.tables.UserRole;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.GRADE</code>.
     */
    public static final Grade GRADE = org.ort.school.crm.jooq.model.tables.Grade.GRADE;

    /**
     * The table <code>PUBLIC.GROUP_STUDENT</code>.
     */
    public static final GroupStudent GROUP_STUDENT = org.ort.school.crm.jooq.model.tables.GroupStudent.GROUP_STUDENT;

    /**
     * The table <code>PUBLIC.PARENT</code>.
     */
    public static final Parent PARENT = org.ort.school.crm.jooq.model.tables.Parent.PARENT;

    /**
     * The table <code>PUBLIC.PARENT_GRADE</code>.
     */
    public static final ParentGrade PARENT_GRADE = org.ort.school.crm.jooq.model.tables.ParentGrade.PARENT_GRADE;

    /**
     * The table <code>PUBLIC.PARENT_STUDENT</code>.
     */
    public static final ParentStudent PARENT_STUDENT = org.ort.school.crm.jooq.model.tables.ParentStudent.PARENT_STUDENT;

    /**
     * The table <code>PUBLIC.ROLE</code>.
     */
    public static final Role ROLE = org.ort.school.crm.jooq.model.tables.Role.ROLE;

    /**
     * The table <code>PUBLIC.STUDENT</code>.
     */
    public static final Student STUDENT = org.ort.school.crm.jooq.model.tables.Student.STUDENT;

    /**
     * The table <code>PUBLIC.USER</code>.
     */
    public static final User USER = org.ort.school.crm.jooq.model.tables.User.USER;

    /**
     * The table <code>PUBLIC.USER_ROLE</code>.
     */
    public static final UserRole USER_ROLE = org.ort.school.crm.jooq.model.tables.UserRole.USER_ROLE;

    /**
     * The table <code>PUBLIC.group</code>.
     */
    public static final Group GROUP = org.ort.school.crm.jooq.model.tables.Group.GROUP;
}
