/*
 * This file is generated by jOOQ.
 */
package org.ort.school.crm.jooq.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.ort.school.crm.jooq.model.Indexes;
import org.ort.school.crm.jooq.model.Keys;
import org.ort.school.crm.jooq.model.Public;
import org.ort.school.crm.jooq.model.tables.records.GradeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Grade extends TableImpl<GradeRecord> {

    private static final long serialVersionUID = 467809241;

    /**
     * The reference instance of <code>public.grade</code>
     */
    public static final Grade GRADE = new Grade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GradeRecord> getRecordType() {
        return GradeRecord.class;
    }

    /**
     * The column <code>public.grade.id</code>.
     */
    public final TableField<GradeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('grade_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.grade.grade_no</code>.
     */
    public final TableField<GradeRecord, Integer> GRADE_NO = createField("grade_no", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.grade.grade_letter</code>.
     */
    public final TableField<GradeRecord, String> GRADE_LETTER = createField("grade_letter", org.jooq.impl.SQLDataType.VARCHAR(1).nullable(false), this, "");

    /**
     * Create a <code>public.grade</code> table reference
     */
    public Grade() {
        this(DSL.name("grade"), null);
    }

    /**
     * Create an aliased <code>public.grade</code> table reference
     */
    public Grade(String alias) {
        this(DSL.name(alias), GRADE);
    }

    /**
     * Create an aliased <code>public.grade</code> table reference
     */
    public Grade(Name alias) {
        this(alias, GRADE);
    }

    private Grade(Name alias, Table<GradeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Grade(Name alias, Table<GradeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Grade(Table<O> child, ForeignKey<O, GradeRecord> key) {
        super(child, key, GRADE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GRADE_GRADE_NO_GRADE_LETTER_KEY, Indexes.GRADE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GradeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GradeRecord> getPrimaryKey() {
        return Keys.GRADE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GradeRecord>> getKeys() {
        return Arrays.<UniqueKey<GradeRecord>>asList(Keys.GRADE_PKEY, Keys.GRADE_GRADE_NO_GRADE_LETTER_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Grade as(String alias) {
        return new Grade(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Grade as(Name alias) {
        return new Grade(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Grade rename(String name) {
        return new Grade(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Grade rename(Name name) {
        return new Grade(name, null);
    }
}
