/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.ort.school

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main() {
    println(App().greeting)
}
